### ISSUE TITLE
新規album登録APIを実装して例会ちゃんに自動でアルバムをcreateしてもらう

### ISSUE THREAD

**Issue by kosamega** [kosamega/Kitchotify_app#126]

**Comment by alkshmir** [comment]
これって月吉の聞き大会の日になったら自動で月吉nnnが作られるようになって欲しいってことですか？

**Comment by kosamega** [comment]
そうですね。
アルバム名と聴き大会の日をパラメータに含めてポストしたらKitchotifyがアルバム作成して、アルバムのURLを返して、そのURLを例会ちゃんがアナウンスみたいなことになったら良いなと。

**Comment by alkshmir** [comment]
現状の実装だと複数回postされちゃうことがあるので2回目以降は弾いてもらえるとやりやすい
実装がダサいというのは重々承知してますが………

**Comment by kosamega** [comment]
> 現状の実装だと複数回postされちゃうことがあるので2回目以降は弾いてもらえるとやりやすい 実装がダサいというのは重々承知してますが………

Kitchotify Create API実装してREADMEに仕様書を追加してみました。
複数回ポストされた場合二回目以降は409が返ってくるはずです。
お暇なときに見てもらって意見もらえると助かります。
https://github.com/kosamega/Kitchotify_app#kitchotify-create-api

**Comment by alkshmir** [comment]
テストで何回か叩くと思うんですがいらんアルバムはこちらで消せますか？
それとも頼めば消してもらえる？

**Comment by kosamega** [comment]
そちらで消せた方が便利そうで、Robertなんちゃらさんをadmin userにしました。
エディターモードをオンにした状態でアルバムのページに行くと「アルバムを編集」ボタンがページ下部に出て、とんだ先に削除ボタンがあります。よろしくお願いします🙇‍♂️
![スクリーンショット 2023-02-15 231301](https://user-images.githubusercontent.com/104709001/219051211-56dbb07e-c75c-4f0a-8d0b-1399c0f36ff0.png)
![スクリーンショット 2023-02-15 231317](https://user-images.githubusercontent.com/104709001/219051240-b0deed2d-53c8-429a-af9e-4cf4a5713f33.png)

**Comment by alkshmir** [comment]
https://github.com/alkshmir/reikai_chan/pull/44
でアルバム作成とindexフォームの周知を追加しました。
テストしきれてないのでしばらく様子見してバグってなさそうならcloseということで…

**Comment by kosamega** [comment]
ありがとうございます！！！了解です！！！！

**Comment by kosamega** [comment]
いい感じっぽいので閉じます（感謝）

**Comment by alkshmir** [comment]
LGTM
