### ISSUE TITLE
同名のアーティストを複数人追加できる

### ISSUE THREAD

**Issue by alkshmir** [kosamega/Kitchotify_app#139]
同名のアーティストを追加できちゃった

- https://kitchotify-app.herokuapp.com/artists/37 
- https://kitchotify-app.herokuapp.com/artists/114

## How to reproduce
/albums/41/musics/new で新規名義で既存のアーティストを追加する

**Comment by kosamega** [comment]
あ～
同名のアーティスト入ってくる可能性あるかな～と思ってそうなってるんですが、それはそれとして今アーティストのnameで検索してる部分があってヤバいですね。
いろいろややこしいのでとりあえず同名のアーティストは追加出来ないようにして、同名のアーティスト入ってくるまでに良い感じにしようと思います（感謝）
